apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman
  template:
    metadata:
      labels:
        app: fleetman
    spec:
      containers:
      - name: fleetman-api-gateway
        image: supinfo4kube/api-gateway:1.0.0
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "production-microservice"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  labels:
    app: fleetman
spec:
  type: NodePort
  selector:
    app: fleetman
  ports:
    - port: 8080
      targetPort: 8080
