apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
      - name: fleetman-queue
        image: supinfo4kube/queue:1.1.0
        ports:
        - containerPort: 8161
        - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
  - name: "61616"
    port: 61616
    targetPort: 61616
  - name: "8161"
    port: 8161
    targetPort: 8161