apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
    component: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman
      component: queue
  template:
    metadata:
      labels:
        app: fleetman
        component: queue
    spec:
      containers:
      - name: queue
        image: supinfo4kube/queue:1.1.0
        ports:
        - containerPort: 61616
        - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
    component: queue
spec:
  type: NodePort
  selector:
    app: fleetman
    component: queue
  ports:
  - name: messaging
    port: 61616
    targetPort: 61616
  - name: admin
    port: 8161
    targetPort: 8161