apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman
  template:
    metadata:
      labels:
        app: fleetman
    spec:
      containers:
      - name: fleetman-webapp
        image: supinfo4kube/web-app:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  selector:
    app: fleetman
  ports:
    - port: 80
      targetPort: 80
