apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-web-app
  template:
    metadata:
      labels:
        app: fleetman-web-app
    spec:
      containers:
      - name: fleetman-web-app
        image: supinfo4kube/web-app:1.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
spec:
  type: NodePort
  selector:
    app: fleetman-web-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
