apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
  labels:
    app: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: fleetman-api-gateway
        image: supinfo4kube/api-gateway:1.1.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  labels:
    app: fleetman-api-gateway
spec:
  selector:
    app: fleetman-api-gateway
  ports:
  - port: 30020
    targetPort: 8080