apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  labels:
    app: fleetman
    component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman
      component: mongodb
  template:
    metadata:
      labels:
        app: fleetman
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  labels:
    app: fleetman
    component: mongodb
spec:
  type: ClusterIP
  selector:
    app: fleetman
    component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    app: fleetman
    component: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  labels:
    app: fleetman
    component: mongodb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mongo-data-pv