apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman
  template:
    metadata:
      labels:
        app: fleetman
    spec:
      containers:
      - name: fleetman-position-simulator
        image: supinfo4kube/position-simulator:1.0.0
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production-microservice"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  type: ClusterIP
  selector:
    app: fleetman
  ports:
    - port: 8080
      targetPort: 8080
